### ISSUE TITLE
TypeError: constrain() missing 1 required positional argument: 'site'

### ISSUE THREAD

**Issue by Yu3H0** [jkrshnmenon/arbiter#7]
when I run CWE190_juliet_signed.py in your dataset like CWE190_s01, I get an error like this:
```
Traceback (most recent call last):
  File "../../test_scripts/test_juliet_190_signed.py", line 78, in <module>
    do_stuff(sys.argv[1])
  File "../../test_scripts/test_juliet_190_signed.py", line 66, in do_stuff
    se.run_all()
  File "/usr/local/lib/python3.8/dist-packages/arbiter-0.0.1-py3.8.egg/arbiter/master_chief/symbolic_execution.py", line 456, in run_all
  File "/usr/local/lib/python3.8/dist-packages/arbiter-0.0.1-py3.8.egg/arbiter/master_chief/symbolic_execution.py", line 446, in run_one
  File "/usr/local/lib/python3.8/dist-packages/arbiter-0.0.1-py3.8.egg/arbiter/master_chief/symbolic_execution.py", line 429, in _execute_one
  File "/usr/local/lib/python3.8/dist-packages/arbiter-0.0.1-py3.8.egg/arbiter/master_chief/symbolic_execution.py", line 286, in _explore_one
  File "/usr/local/lib/python3.8/dist-packages/arbiter-0.0.1-py3.8.egg/arbiter/master_chief/symbolic_execution.py", line 251, in _check_state
  File "/usr/local/lib/python3.8/dist-packages/arbiter-0.0.1-py3.8.egg/arbiter/master_chief/symbolic_execution.py", line 172, in _apply_sz_constraints
TypeError: constrain() missing 1 required positional argument: 'site'
```
So I change the code in symbolic_execution.py, however, I get another erro when I run test_arbiter.py, so how can I run the code correctely

**Comment by jkrshnmenon** [comment]
The only time I've had to use the `site` argument was in the Juliet CWE190 Signed test cases because of the different sinks and the different data type sizes that each sink uses.
But I feel like this information might be necessary in more than just a few cases.
For now, commit [f5a9c13](https://github.com/jkrshnmenon/arbiter/commit/f5a9c136891a00a426754260a93d38c9aeefda3b) should fix this issue. I'll keep working on a more generic solution in the meanwhile.

Thanks for pointing this out.

**Comment by Yu3H0** [comment]
Thanks for your reply！
